FROM golang:1.21-bullseye AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

FROM scratch
WORKDIR /
COPY --from=builder /app/main /main
COPY --from=builder /app/templates /templates
EXPOSE 8080
CMD ["/main"]
